package jehr.projects.musicus.utils

private val exampleData = listOf(
    TrackSkeleton(
        path = "",
        name = "Goodbye Sengen",
        originalName = "Insert original name",
        lang = mutableListOf("English"),
        origin = "Single",
        originInfo = "OC Eng. Ver.",
        runtime = Duration(0, 3, 30, 0),
        cover = true,
        originalLang = mutableListOf("Japanese"),
        album = "Stetson's Hats",
        playlists = mutableListOf("Songza JP", "Songza All"),
        artists = mutableListOf("Will Stetson"),
        imgPath = null,
        dateAdded = MusicusDate(13, 8, 2025),
        timesPlayed = 0,
        stdLyrics = null,
        trnLyrics = null,
        romLyrics = null,
        selectedLyrics = 0,
        desc = "Hikikomori is the way of justice!"
    ),
    TrackSkeleton(
        path = "",
        name = "Camel By Camel",
        originalName = null,
        lang = mutableListOf("English"),
        origin = "Single",
        originInfo = null,
        runtime = Duration(0, 4, 30, 505),
        cover = false,
        originalLang = mutableListOf(),
        album = "Dune Tunes",
        playlists = mutableListOf("Songza EN", "Songza All"),
        artists = mutableListOf("Sandy Marton"),
        imgPath = null,
        dateAdded = MusicusDate(13, 8, 2025),
        timesPlayed = 0,
        stdLyrics = null,
        trnLyrics = null,
        romLyrics = null,
        selectedLyrics = 1,
        desc = null
    ),
    TrackSkeleton(
        path = "",
        name = "I'm The Rain",
        originalName = "Insert Japanese stuff",
        lang = mutableListOf("Japanese"),
        origin = "Single",
        originInfo = null,
        runtime = Duration(0, 3, 10, 123),
        cover = false,
        originalLang = mutableListOf("Japanese"),
        album = "Right Fine Weather We're Having",
        playlists = mutableListOf("Songza JP", "Songza All"),
        artists = mutableListOf("inabakumori"),
        imgPath = null,
        dateAdded = MusicusDate(13, 8, 2025),
        timesPlayed = 0,
        stdLyrics = null,
        trnLyrics = null,
        romLyrics = null,
        selectedLyrics = 2,
        desc = null
    ),
    TrackSkeleton(
        path = "",
        name = "Young Girl A",
        originalName = null,
        lang = mutableListOf("English"),
        origin = "Single",
        originInfo = "OC Eng. Ver.",
        runtime = Duration(0, 2, 55, 3),
        cover = true,
        originalLang = mutableListOf("Japanese"),
        album = "Stetson's Hats",
        playlists = mutableListOf("Songza EN", "Songza All"),
        artists = mutableListOf("Will Stetson"),
        imgPath = null,
        dateAdded = MusicusDate(13, 8, 2025),
        timesPlayed = 0,
        stdLyrics = null,
        trnLyrics = null,
        romLyrics = null,
        selectedLyrics = 0,
        desc = "The things that happened and will not happen again."
    ),
    TrackSkeleton(
        path = "",
        name = "Odo",
        originalName = "Odo But In Japanese",
        lang = mutableListOf("Japanese"),
        origin = "Single",
        originInfo = null,
        runtime = Duration(0, 3, 40, 300),
        cover = false,
        originalLang = mutableListOf(),
        album = null,
        playlists = mutableListOf(),
        artists = mutableListOf("Ado"),
        imgPath = null,
        dateAdded = MusicusDate(13, 8, 2025),
        timesPlayed = 0,
        stdLyrics = null,
        trnLyrics = null,
        romLyrics = null,
        selectedLyrics = 0,
        desc = null
    ),
    TrackSkeleton(
        path = "",
        name = "Lost Umbrella",
        originalName = "Lost Umbrella But In Japanese",
        lang = mutableListOf("Japanese"),
        origin = "Single",
        originInfo = null,
        runtime = Duration(0, 3, 20, 500),
        cover = false,
        originalLang = mutableListOf(),
        album = "Right Fine Weather We're Having",
        playlists = mutableListOf("Songza JP", "Songza All"),
        artists = mutableListOf("inabakumori"),
        imgPath = null,
        dateAdded = MusicusDate(13, 8, 2025),
        timesPlayed = 0,
        stdLyrics = null,
        trnLyrics = null,
        romLyrics = null,
        selectedLyrics = 1,
        desc = "The longing to ruminate among the raindrops."
    )
)

val exJSONContainer = JsonContainer(
    exampleData,
    listOf(),
    listOf(),
    listOf()
)